In [25]:
import requests
import pandas as pd
from datetime import datetime

In [6]:
url = 'https://api.performfeeds.com/soccerdata/match/1u2vu9dy9um7r1galdsvmxmdkm?_rt=c&_fmt=json&_lcl=en-gb&lineups=no&live=yes&comp=djkvh1luqdkdixpoe653lzixg%2C85qdzpr6i56z8tjex9d5mu5pm%2C135j6qi3ap8i3vc9hwdo4fjtg&_pgSz=250&_pgNm=1&mt.mDt=%5B2026-01-16T08%3A00%3A00.000Z+TO+2026-12-01T06%3A59%3A59.999Z%5D'

# Define the headers as a dictionary
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    'Accept': 'application/json',
    'Referer': 'https://live.opta.statsperform.com/',
}

response = requests.get(url, headers=headers)

In [9]:
raw = response.json()

In [32]:
def format_match(match):
    date=match['matchInfo']['localDate']
    time=datetime.strptime(match['matchInfo']['localTime'], '%H:%M:%S')
    time=time.strftime('%I:%M %p')
    home=match['matchInfo']['contestant'][0]['code']
    away=match['matchInfo']['contestant'][1]['code']
    
    return [date, time, home, away]

In [29]:
df = pd.DataFrame([], columns=["date", "time", "home", "away"])
for match in raw['match']:
    df.loc[len(df)] =format_match(match)

df

           date      time home away
0    2026-11-01  05:00 PM  WAS  CHI
1    2026-11-01  02:00 PM  SEA  ORL
2    2026-11-01  05:00 PM   NC  DEN
3    2026-11-01  05:00 PM  LOU   KC
4    2026-11-01  02:00 PM   LA  BOS
..          ...       ...  ...  ...
236  2026-03-14  07:00 PM   NC  LOU
237  2026-03-14  03:30 PM  BAY  DEN
238  2026-03-14  03:00 PM   KC  UTA
239  2026-03-14  12:30 PM  BOS  GFC
240  2026-03-13  08:00 PM  WAS  POR

[241 rows x 4 columns]

In [31]:
df = df.sort_values('date')
df

           date      time home away
240  2026-03-13  08:00 PM  WAS  POR
235  2026-03-14  05:45 PM   SD  HOU
236  2026-03-14  07:00 PM   NC  LOU
239  2026-03-14  12:30 PM  BOS  GFC
238  2026-03-14  03:00 PM   KC  UTA
..          ...       ...  ...  ...
4    2026-11-01  02:00 PM   LA  BOS
3    2026-11-01  05:00 PM  LOU   KC
2    2026-11-01  05:00 PM   NC  DEN
1    2026-11-01  02:00 PM  SEA  ORL
0    2026-11-01  05:00 PM  WAS  CHI

[241 rows x 4 columns]

In [34]:
df = df.replace({'SEA': 'RGN', 'KC': 'KCC'})

In [35]:
df.to_csv("data/2026_schedule.csv", index=False)